import fs from 'fs';
import { join } from 'path';
import vars from '../less-variables';

let lessContent = '// Generated by @ali/antd-kaitian-theme\n\n';

Object.keys(vars).forEach(key => {
  const value = vars[key];
  lessContent += `${key}: ${value};\n`;
});

fs.writeFileSync(join(process.cwd(), 'index.less'), lessContent);
// eslint-disable-next-line no-console
console.log('✨ Generated index.less successfully!');
